name: Pipeline

on:
  push:
    branches: []
  pull_request:
    branches: [main]

jobs:
  Sonar-Scan:
    runs-on: ubuntu-latest
    steps:
      #Base checkout action repo
      - uses: actions/checkout@v2
      # Scan the code with sonar Cloud
      - name: Sonar Cloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: |
            -Dsonar.organization=doublest-github
            -Dsonar.projectKey=doublest_RESTfulBlogApp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Build Docker Image from Dockerfile
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      # Push to DockerHub
  Push-to-DockerHub:
    runs-on: ubuntu-latest
    steps:
      - name: Push to DockerHub Repo
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USER }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "doublest/restfulblogapp"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
