name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildPushContainer:
    runs-on: ubuntu-latest
    steps:
      #Base checkout action repo
      - name: check out actions repo
      - uses: actions/checkout@v2

      # Build Docker Image based on Dockerfile in repo
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      # Push to DockerHub
      - name: Push to DockerHub Repo
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USER }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "doublest/restfulblogapp"
          TAG_NAME: "v0.0.1"
          LATEST: "true"

      # Scan the code with sonar Cloud
      - name: Sonar Cloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: -Dsonar.organization=doublest-github
            -Dsonar.projectKey=doublest_RESTfulBlogApp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
