name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Push to DockerHub Repo
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USER }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY: "https://hub.docker.com/repository/docker/doublest/restfulblogapp"
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "doublest/blog-app"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
